# Generated by Django 3.1.8 on 2021-07-28 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectionofflashcards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionofflashcards',
            name='description',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='collectionofflashcards',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
